#!/usr/bin/zsh

mainmenu()
{
	opt=$(dialog --nocancel --title "Main Menu" --menu \
		"Choose one of the following options:" 0 0 0 \
		1 'Add a new book' 2 'View book stack' \
		3 'Edit book stack' 4 'Reorder books' \
		5 'Search books' \
		6 'Exit' \
		3>&1 1>&2 2>&3 3>&1) 
	if [[ $opt == 1 ]]
	then
		addbook
	elif [[ $opt == 2 ]]
	then
		bookstack
	elif [[ $opt == 3 ]]
	then
		editstack
	elif [[ $opt == 4 ]]
	then
		orderstack
	elif [[ $opt == 5 ]]
	then
		search
	elif [[ $opt == 6 ]]
	then
		exit
	fi
}

addbook()
{
	bp=$(dialog --fselect /home/ 30 150 \
		3>&1 1>&2 2>&3 3>&1)
	if [[ $bp == "" ]]
	then
		mainmenu
	fi
	filename=`basename "$bp" | sed 's/\.[^.]*$//'`
	ba=$(dialog --inputbox \
		"Enter book's author(s)" 10 100 $filename \
		3>&1 1>&2 2>&3 3>&1)
	if [[ $ba == "" ]]
	then
		mainmenu
	fi
	bt=$(dialog --inputbox \
		"Enter book's title:" 10 100 $filename \
		3>&1 1>&2 2>&3 3>&1)
	if [[ $bt == "" ]]
	then
		mainmenu
	fi
	if [[ $bp != "" ]] && [[ $ba != "" ]] && [[ $bt != "" ]]
	then
		echo $bp >> texts/file_path.txt
		echo $ba >> texts/author.txt
		echo $bt >> texts/title.txt
	fi
	bookstack
}

listing()
{
	count=0
	a_arr=()
	while IFS="\n" read -r author
	do
		count=$[count + 1]
		a_arr+=($author )
	done < texts/author.txt

	t_arr=()
	while IFS="\n" read -r title
	do
		t_arr+=($title )
	done < texts/title.txt

	str=''
	menuopt=()
	for i in $(seq 1 $count)
	do
		str="${a_arr[$i]} - ${t_arr[$i]}"
		menuopt+=($i $str )
	done
}

listingse()
{
	grepawk=`grep -n $inp texts/$txt | awk -F ":" '{print $1}'`
	if [[ $grepawk == "" ]]
	then
		dialog --msgbox "$inp not found." 0 0
		search
	else
		count=0
		arr=()
		str=''
		while IFS="\n" read -r ln
		do
			count=$[count + 1]
			ttl=`awk NR==$ln texts/title.txt`
			aut=`awk NR==$ln texts/author.txt`
			str="$aut - $ttl"
			arr+=($ln $str )
		done <<< $grepawk
		if [[ ${arr} == "" ]]
		then
			dialog --msgbox "Add a book first." 0 0 
			mainmenu
		else
			searchstack
		fi
	fi
}

bookstack()
{
	listing
	if [[ ${menuopt} == "" ]]
	then
		dialog --msgbox "Add a book first." 0 0 
		mainmenu
	fi
	choices=$(dialog --title "Book Stack" --cancel-label "Main Menu" --menu \
		"Select a book to read:" 0 0 $count ${menuopt} \
		3>&1 1>&2 2>&3 3>&1)
	ifopt
}

editstack()
{
	listing
	if [[ ${menuopt} == "" ]]
	then
		dialog --msgbox "Add a book first." 0 0 
		mainmenu
	fi
	choices=$(dialog --ascii-lines --title "Edit Book Stack" --cancel-label "Main Menu" --menu \
		"Select a book to edit:" 0 0 $count ${menuopt} \
		3>&1 1>&2 2>&3 3>&1)
	ifopt
}

orderstack()
{
	listing
	if [[ ${menuopt} == "" ]]
	then
		dialog --msgbox "Add a book first." 0 0 
		mainmenu
	fi
	choices=$(dialog --no-lines --title "Reorder Books" --cancel-label "Main Menu" --menu \
		"Select a book to move:" 0 0 $count ${menuopt} \
		3>&1 1>&2 2>&3 3>&1)
	ifopt
}

searchstack()
{
	choices=$(dialog --title "Book Stack" --cancel-label "Main Menu" --menu \
		"Select a book to read:" 0 0 $count ${arr} \
		3>&1 1>&2 2>&3 3>&1)
	ifopt
}


ifopt()
{
	if [[ $choices != "" ]]
	then
		if [[ $opt == 1 ]] || [[ $opt == 2 ]]
		then
			readbook
		elif [[ $opt == 3 ]]
		then
			edit
		elif [[ $opt == 4 ]]
		then
			reorder
		elif [[ $opt == 5 ]]
		then
			readbookse
		fi
	else
		mainmenu
	fi
}

readbook()
{
	count=0
	while IFS="\n" read -r bookpath
	do
		count=$[count + 1]
		if [[ $count == $choices ]]
		then
			zathura $bookpath
			bookstack
		fi
	done < texts/file_path.txt
	if [[ $choices == "" ]]
	then
		mainmenu
	fi
}

readbookse()
{
	count=0
	while IFS="\n" read -r bookpath
	do
		count=$[count + 1]
		if [[ $count == $choices ]]
		then
			zathura $bookpath
			searchstack
		fi
	done < texts/file_path.txt
	if [[ $choices == "" ]]
	then
		mainmenu
	fi
}

edit()
{
	editmenu=$(dialog --ascii-lines --cancel-label "Back" --menu \
		"Choose one of the following options:" 0 0 0 \
		1 'Edit author' 2 'Edit title' 3 'Edit file path' 4 'Delete book' \
		3>&1 1>&2 2>&3 3>&1)
	if [[ $editmenu == 1 ]]
	then
		toedit=`awk NR==$choices texts/author.txt`
		ea=$(dialog --ascii-lines --inputbox \
			"Enter book's author(s)" 10 100 $toedit \
			3>&1 1>&2 2>&3 3>&1)
		if [[ $ea != "" ]]
		then
			sed -i "$choices"\s"/$toedit/$ea/" texts/author.txt
		fi
		edit
	elif [[ $editmenu == 2 ]]
	then
		toedit=`awk NR==$choices texts/title.txt`
		et=$(dialog --ascii-lines --inputbox \
			"Enter book's title" 10 100 $toedit \
			3>&1 1>&2 2>&3 3>&1)
		if [[ $et != "" ]]
		then
			sed -i "$choices"\s"/$toedit/$et/" texts/title.txt
		fi
		edit
	elif [[ $editmenu == 3 ]]
	then
		toedit=`awk NR==$choices texts/file_path.txt`
		ef=$(dialog --ascii-lines --fselect $toedit 30 150 \
			3>&1 1>&2 2>&3 3>&1)
		if [[ $ef != "" ]]
		then
			sed -i "$choices"\s">$toedit>$ef>" texts/file_path.txt
		fi
		edit
	elif [[ $editmenu == 4 ]]
	then
		sed -i "$choices"\d"" texts/author.txt
		sed -i "$choices"\d"" texts/title.txt
		sed -i "$choices"\d"" texts/file_path.txt
		editstack
	else
		editstack
	fi
}

reorder()
{
	choices2=$(dialog --no-lines --title "Reorder Books" --cancel-label "Main Menu" --menu \
		"Select position:" 0 0 $count ${menuopt} \
		3>&1 1>&2 2>&3 3>&1)
	if [[ $choices2 == "" ]]
	then
		orderstack
	fi
	if [[ $choices == $choices2 ]]
	then
		orderstack
	fi
	if [[ $choices -gt $choices2 ]]
	then
		for i in author.txt title.txt file_path.txt
		do
			var=`awk NR==$choices texts/$i`
			sed -i "$choices"\d"" texts/$i
			sed -i "$choices2 i $var" texts/$i
		done

	elif [[ $choices -lt $choices2 ]]
	then
		for i in author.txt title.txt file_path.txt
		do
			sed -i "$choices{h;d}; $choices2{p;x}" texts/$i
		done
	fi
	orderstack
}

search()
{
	semenu=$(dialog --title "Search Books" --cancel-label "Main Menu" --menu \
		"Choose one option:" 0 0 2 \
		1 'Search for books by title' 2 'Search for books by author' \
		3>&1 1>&2 2>&3 3>&1)
	if [[ $semenu == "" ]]
	then
		mainmenu
	elif [[ $semenu == 1 ]]
	then
		inp=$(dialog --inputbox \
			"Enter book's title" 10 100 \
			3>&1 1>&2 2>&3 3>&1)
		if [[ $inp == "" ]]
		then
			mainmenu
		else
			txt="title.txt"
			listingse
		fi
	elif [[ $semenu == 2 ]]
	then
		inp=$(dialog --inputbox \
			"Enter book's author" 10 100 \
			3>&1 1>&2 2>&3 3>&1)
		if [[ $inp == "" ]]
		then
			mainmenu
		else
			txt="author.txt"
			listingse
		fi
	fi
}

mainmenu
